export const BookItem = [
  {
    bookId: "1",
    title: "How to create a Java Application",
    description: "This book will teach you about Java",
    author: "Foo Man the third",
    year: "1999",
    imageUrl: "https://m.media-amazon.com/images/I/51eS3MxQ1YL.jpg",
    price: "100,00 kr",
    city: "Rødovre",
    country: "Denmark",
  },
  {
    bookId: "2",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "3",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "4",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "5",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "6",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "7",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "8",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "9",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "10",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
  {
    bookId: "11",
    title: "Parallel Programming and you",
    description: "Programming in a parallel world",
    author: "Horseman Jack",
    year: "2008",
    imageUrl:
      "https://images-na.ssl-images-amazon.com/images/I/41gr4XJnUjL._SX321_BO1,204,203,200_.jpg",
    price: "250,00 kr",
    city: "Horsens",
    country: "Denmark",
  },
];
